### ISSUE TITLE
理想汽车求贤

### ISSUE THREAD

**Issue by boyanking** [zzzbwbzzz/officeOnline#8]
李帆您好：
我是理想汽车前端研发部门负责人 王文君 
看到你做的这些项目非常符合我这边的技术规划。
我们急需excel online、项目管理工具、3D轻量化等工具开发人才。
能效工程部门急需负责人和若干高级开发。
如果您有兴趣可以联系我
王文君，电话：18600130145
坐标：北京

**Comment by zzzbwbzzz** [comment]
非常感谢您的抬爱，也很抱歉将近一年才回复您。我是去年十二月看到您的消息，您提供的岗位确实让我很心动，但由于一些原因，犹豫了很久才回复您。我可能无法前往贵司应聘。理由如下：
1、由于去年经历了艰难的求职之路，所以对换工作有一点抵触。当时难得获得了一份稳定的工作，所以没有立即回复您。
2、我自毕业后一直在苏州，距离北京太远。
3、虽然我对前端开发有一定的经验，但是还是希望能在后台开发有一定的发展。
希望您能谅解，抱歉。

**Comment by boyanking** [comment]
希望有机会合作
